// <auto-generated />
using System;
using LogiEdge.Service.DocumentGenerator.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogiEdge.Service.DocumentGenerator.Migrations
{
    [DbContext(typeof(DocumentGeneratorDbContext))]
    [Migration("20260613092940_DocumentTemplates")]
    partial class DocumentTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogiEdge.Service.DocumentGenerator.Data.DocumentGenerationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("InputTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DocumentTemplates");

                    b.HasDiscriminator().HasValue("DocumentGenerationTemplate");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogiEdge.Service.DocumentGenerator.Data.HtmlDocumentGenerationTemplate", b =>
                {
                    b.HasBaseType("LogiEdge.Service.DocumentGenerator.Data.DocumentGenerationTemplate");

                    b.Property<string>("FooterCenter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FooterLeft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FooterRight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderCenter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderLeft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderRight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("HtmlDocumentGenerationTemplate");
                });
#pragma warning restore 612, 618
        }
    }
}
