// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using LogiEdge.WarehouseService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogiEdge.WarehouseService.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20250508090344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogiEdge.CustomerService.Data.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InventoryTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ItemSchemaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InventoryTransactionId");

                    b.HasIndex("ItemSchemaId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.ItemSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("AdditionalPropertiesTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("ItemSchemas");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.ItemState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("RelatedTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RelatedTransactionId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ItemState");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("AttachmentIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<JsonElement?>("DraftItems")
                        .HasColumnType("jsonb");

                    b.Property<string>("HandledByWorker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InventoryTransaction");

                    b.HasDiscriminator().HasValue("InventoryTransaction");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.InboundTransaction", b =>
                {
                    b.HasBaseType("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction");

                    b.HasDiscriminator().HasValue("InboundTransaction");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.OutboundTransaction", b =>
                {
                    b.HasBaseType("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction");

                    b.HasDiscriminator().HasValue("OutboundTransaction");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.RelocationTransaction", b =>
                {
                    b.HasBaseType("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction");

                    b.HasDiscriminator().HasValue("RelocationTransaction");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Item", b =>
                {
                    b.HasOne("LogiEdge.CustomerService.Data.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", null)
                        .WithMany("AffectedItems")
                        .HasForeignKey("InventoryTransactionId");

                    b.HasOne("LogiEdge.WarehouseService.Data.ItemSchema", "ItemSchema")
                        .WithMany()
                        .HasForeignKey("ItemSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiEdge.WarehouseService.Data.Warehouse", null)
                        .WithMany("Items")
                        .HasForeignKey("WarehouseId");

                    b.Navigation("Customer");

                    b.Navigation("ItemSchema");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.ItemState", b =>
                {
                    b.HasOne("LogiEdge.WarehouseService.Data.Item", "Item")
                        .WithMany("ItemStates")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", "RelatedTransaction")
                        .WithMany("NewItemStates")
                        .HasForeignKey("RelatedTransactionId");

                    b.HasOne("LogiEdge.WarehouseService.Data.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RelatedTransaction");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Item", b =>
                {
                    b.Navigation("ItemStates");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", b =>
                {
                    b.Navigation("AffectedItems");

                    b.Navigation("NewItemStates");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Warehouse", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
