// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using LogiEdge.WarehouseService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogiEdge.WarehouseService.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20260604124608_AddBookedDate")]
    partial class AddBookedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerItemSchema", b =>
                {
                    b.Property<Guid>("CustomersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemSchemaId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomersId", "ItemSchemaId");

                    b.HasIndex("ItemSchemaId");

                    b.ToTable("CustomerItemSchema");
                });

            modelBuilder.Entity("LogiEdge.CustomerService.Data.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InventoryTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Retracted")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventoryTransactionId");

                    b.HasIndex("ItemId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ItemSchemaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OutboundTransactionPartId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ItemSchemaId");

                    b.HasIndex("OutboundTransactionPartId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.ItemSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("ItemSchemas");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.ItemState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InboundTransactionPartId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("OutboundTransactionPartId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelocationTransactionPartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InboundTransactionPartId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OutboundTransactionPartId");

                    b.HasIndex("RelatedTransactionId");

                    b.HasIndex("RelocationTransactionPartId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ItemState");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.InboundDraftItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboundTransactionPartId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ItemSchemaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InboundTransactionPartId");

                    b.HasIndex("ItemSchemaId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InboundDraftItem");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.InboundTransactionPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("InboundTransactionPart");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("AttachmentIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime?>("BookedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HandledByWorker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InboundTransactionPartId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OutboundTransactionPartId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelocationTransactionPartId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("InboundTransactionPartId")
                        .IsUnique();

                    b.HasIndex("OutboundTransactionPartId")
                        .IsUnique();

                    b.HasIndex("RelocationTransactionPartId")
                        .IsUnique();

                    b.ToTable("InventoryTransactions");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.OutboundTransactionPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Dictionary<string, string>>>("DraftPlaceholderItems")
                        .HasColumnType("hstore[]");

                    b.HasKey("Id");

                    b.ToTable("OutboundTransactionPart");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.RelocationTransactionPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RelocationTransactionPart");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("CustomerItemSchema", b =>
                {
                    b.HasOne("LogiEdge.CustomerService.Data.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiEdge.WarehouseService.Data.ItemSchema", null)
                        .WithMany()
                        .HasForeignKey("ItemSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Comment", b =>
                {
                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", null)
                        .WithMany("Comments")
                        .HasForeignKey("InventoryTransactionId");

                    b.HasOne("LogiEdge.WarehouseService.Data.Item", null)
                        .WithMany("Comments")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Item", b =>
                {
                    b.HasOne("LogiEdge.CustomerService.Data.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiEdge.WarehouseService.Data.ItemSchema", "ItemSchema")
                        .WithMany()
                        .HasForeignKey("ItemSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.OutboundTransactionPart", null)
                        .WithMany("DraftSelectedItems")
                        .HasForeignKey("OutboundTransactionPartId");

                    b.HasOne("LogiEdge.WarehouseService.Data.Warehouse", null)
                        .WithMany("Items")
                        .HasForeignKey("WarehouseId");

                    b.Navigation("Customer");

                    b.Navigation("ItemSchema");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.ItemSchema", b =>
                {
                    b.OwnsMany("LogiEdge.WarehouseService.Data.ItemSchemaProperty", "AdditionalProperties", b1 =>
                        {
                            b1.Property<string>("Name")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsUnique")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("ItemSchemaId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasMaxLength(256)
                                .HasColumnType("integer");

                            b1.HasKey("Name");

                            b1.HasIndex("ItemSchemaId");

                            b1.ToTable("ItemSchemaProperty");

                            b1.WithOwner()
                                .HasForeignKey("ItemSchemaId");
                        });

                    b.Navigation("AdditionalProperties");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.ItemState", b =>
                {
                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.InboundTransactionPart", null)
                        .WithMany("NewItemStates")
                        .HasForeignKey("InboundTransactionPartId");

                    b.HasOne("LogiEdge.WarehouseService.Data.Item", "Item")
                        .WithMany("ItemStates")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.OutboundTransactionPart", null)
                        .WithMany("NewItemStates")
                        .HasForeignKey("OutboundTransactionPartId");

                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", "RelatedTransaction")
                        .WithMany()
                        .HasForeignKey("RelatedTransactionId");

                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.RelocationTransactionPart", null)
                        .WithMany("NewItemStates")
                        .HasForeignKey("RelocationTransactionPartId");

                    b.HasOne("LogiEdge.WarehouseService.Data.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RelatedTransaction");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.InboundDraftItem", b =>
                {
                    b.HasOne("LogiEdge.CustomerService.Data.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.InboundTransactionPart", null)
                        .WithMany("DraftItems")
                        .HasForeignKey("InboundTransactionPartId");

                    b.HasOne("LogiEdge.WarehouseService.Data.ItemSchema", "ItemSchema")
                        .WithMany()
                        .HasForeignKey("ItemSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiEdge.WarehouseService.Data.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ItemSchema");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", b =>
                {
                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.InboundTransactionPart", "InboundTransactionPart")
                        .WithOne("Transaction")
                        .HasForeignKey("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", "InboundTransactionPartId");

                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.OutboundTransactionPart", "OutboundTransactionPart")
                        .WithOne("Transaction")
                        .HasForeignKey("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", "OutboundTransactionPartId");

                    b.HasOne("LogiEdge.WarehouseService.Data.Transactions.RelocationTransactionPart", "RelocationTransactionPart")
                        .WithOne("Transaction")
                        .HasForeignKey("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", "RelocationTransactionPartId");

                    b.Navigation("InboundTransactionPart");

                    b.Navigation("OutboundTransactionPart");

                    b.Navigation("RelocationTransactionPart");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Item", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ItemStates");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.InboundTransactionPart", b =>
                {
                    b.Navigation("DraftItems");

                    b.Navigation("NewItemStates");

                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.InventoryTransaction", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.OutboundTransactionPart", b =>
                {
                    b.Navigation("DraftSelectedItems");

                    b.Navigation("NewItemStates");

                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Transactions.RelocationTransactionPart", b =>
                {
                    b.Navigation("NewItemStates");

                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("LogiEdge.WarehouseService.Data.Warehouse", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
